# Header
menu:
  首页: /
  生活: /life
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive

widgets_post:
- toc

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: