# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: github.com/johnnyfee
  twitter: '#'
  facebook: 'https://www.facebook.com/inesoibags'
  dribbble: '#'
  rss: /atom.xml

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: https://twitter.com/inesoibags
google_plus: https://plus.google.com/101369264801334923510/posts
fb_admins:
fb_app_id: